name = "dose"
description = "a small blog theme"
license = "MIT"
homepage = "https://github.com/oltdaniel/dose"
min_version = "0.13.0"
demo = "https://oltdaniel.github.io/dose"

[extra]
social_media = [
    {name = "GitHub", url = "https://github.com/oltdaniel"},
    {name = "Twitter", url = "https://twitter.com/@twitter"},
]

[author]
name = "oltdaniel"
homepage = "https://oltdaniel.eu"